<?php

namespace common\widgets;

use app\models\Livro;
use yii\base\Widget;

class NavDropdownWidget extends Widget
{
    public $carrinho;

    public function init()
    {
        parent::init();// TODO: Change the autogenerated stub

        foreach ($this->carrinho as $id_livro){
            $query = Livro::findOne($id_livro);

        }

    }
}